-- ─── Migration 002: Admin Panel Metadata ────────────────────────────────────
-- Run this ONCE against your existing database before using the admin panel.
-- Requires MySQL 8.0+  (uses ADD COLUMN IF NOT EXISTS).
-- Safe to re-run — duplicate columns are silently skipped.
-- Add missing columns to posts table
ALTER TABLE
    posts
ADD
    COLUMN IF NOT EXISTS subtitle VARCHAR(500) NULL
AFTER
    title,
ADD
    COLUMN IF NOT EXISTS topic VARCHAR(100) NULL
AFTER
    author_id,
ADD
    COLUMN IF NOT EXISTS episode INT NULL
AFTER
    topic,
ADD
    COLUMN IF NOT EXISTS hashtags JSON NULL
AFTER
    episode;
-- Add password column to users table so admins can log in
ALTER TABLE
    users
ADD
    COLUMN IF NOT EXISTS password_hash VARCHAR(255) NULL
AFTER
    email;
-- ─── Seed your first admin user ──────────────────────────────────────────────
-- Replace the placeholder hash with one generated by bcrypt (cost 12).
-- You can generate a hash with Node.js:
--   node -e "const b=require('bcryptjs');b.hash('yourpassword',12).then(console.log)"
-- Then paste the output (starting with $2a$) below and run this INSERT.
-- INSERT INTO users (name, email, password_hash, role)
-- VALUES ('Sharon', 'you@example.com', '$2a$12$REPLACE_WITH_REAL_HASH', 'admin');